// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb_transporte

import (
	"database/sql"
	

)

type Carrito struct {
	ID            int64
	NombreCarrito string
	Capacidad     int64
	Estado        sql.NullString
	RutaID        sql.NullInt64
}

type Locacione struct {
	ID        int64
	Latitud   float64
	Longitud  float64
	TimeStamp sql.NullTime
	CarritoID int64
}

type Parada struct {
	IDParada int64
	Nombre   string
	Latitud  sql.NullFloat64
	Longitud sql.NullFloat64
}

type Ruta struct {
	ID          int64
	Nombre      string
	Descripcion sql.NullString
}

type Solicitude struct {
	ID            int64
	CedulaUsuario string
	CantPersonas  sql.NullInt64
	ParadaOrigen  sql.NullInt64
	PuntoDestino  sql.NullString
	Estado        sql.NullString
	IDCarrito     sql.NullInt64
}
