// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_locacion.sql

package sqlcdb_transporte

import (
	"context"
	"database/sql"
)

const listarLocaciones = `-- name: ListarLocaciones :many
SELECT id, latitud, longitud, time_stamp, carrito_id FROM locaciones
`

func (q *Queries) ListarLocaciones(ctx context.Context) ([]Locacione, error) {
	rows, err := q.db.QueryContext(ctx, listarLocaciones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Locacione
	for rows.Next() {
		var i Locacione
		if err := rows.Scan(
			&i.ID,
			&i.Latitud,
			&i.Longitud,
			&i.TimeStamp,
			&i.CarritoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerUltimaLocacionPorCarrito = `-- name: ObtenerUltimaLocacionPorCarrito :one
SELECT id, latitud, longitud, time_stamp, carrito_id FROM locaciones WHERE carrito_id = ? ORDER BY time_stamp DESC LIMIT 1
`

func (q *Queries) ObtenerUltimaLocacionPorCarrito(ctx context.Context, carritoID int64) (Locacione, error) {
	row := q.db.QueryRowContext(ctx, obtenerUltimaLocacionPorCarrito, carritoID)
	var i Locacione
	err := row.Scan(
		&i.ID,
		&i.Latitud,
		&i.Longitud,
		&i.TimeStamp,
		&i.CarritoID,
	)
	return i, err
}

const registrarLocacion = `-- name: RegistrarLocacion :one
INSERT INTO locaciones (latitud, longitud, time_stamp, carrito_id) VALUES (?, ?, ?, ?) RETURNING id, latitud, longitud, time_stamp, carrito_id
`

type RegistrarLocacionParams struct {
	Latitud   float64
	Longitud  float64
	TimeStamp sql.NullTime
	CarritoID int64
}

func (q *Queries) RegistrarLocacion(ctx context.Context, arg RegistrarLocacionParams) (Locacione, error) {
	row := q.db.QueryRowContext(ctx, registrarLocacion,
		arg.Latitud,
		arg.Longitud,
		arg.TimeStamp,
		arg.CarritoID,
	)
	var i Locacione
	err := row.Scan(
		&i.ID,
		&i.Latitud,
		&i.Longitud,
		&i.TimeStamp,
		&i.CarritoID,
	)
	return i, err
}
