// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_solicitud.sql

package sqlcdb_transporte

import (
	"context"
	"database/sql"
)

const actualizarSolicitud = `-- name: ActualizarSolicitud :one
UPDATE solicitudes SET cedula_usuario = ?, cant_personas = ?, parada_origen = ?, punto_destino = ?, estado = ?, id_carrito = ? WHERE id = ? RETURNING id, cedula_usuario, cant_personas, parada_origen, punto_destino, estado, id_carrito
`

type ActualizarSolicitudParams struct {
	CedulaUsuario string
	CantPersonas  sql.NullInt64
	ParadaOrigen  sql.NullInt64
	PuntoDestino  sql.NullString
	Estado        sql.NullString
	IDCarrito     sql.NullInt64
	ID            int64
}

func (q *Queries) ActualizarSolicitud(ctx context.Context, arg ActualizarSolicitudParams) (Solicitude, error) {
	row := q.db.QueryRowContext(ctx, actualizarSolicitud,
		arg.CedulaUsuario,
		arg.CantPersonas,
		arg.ParadaOrigen,
		arg.PuntoDestino,
		arg.Estado,
		arg.IDCarrito,
		arg.ID,
	)
	var i Solicitude
	err := row.Scan(
		&i.ID,
		&i.CedulaUsuario,
		&i.CantPersonas,
		&i.ParadaOrigen,
		&i.PuntoDestino,
		&i.Estado,
		&i.IDCarrito,
	)
	return i, err
}

const borrarSolicitud = `-- name: BorrarSolicitud :execrows
DELETE FROM solicitudes WHERE id = ?
`

func (q *Queries) BorrarSolicitud(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarSolicitud, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarSolicitudPorID = `-- name: BuscarSolicitudPorID :one
SELECT id, cedula_usuario, cant_personas, parada_origen, punto_destino, estado, id_carrito FROM solicitudes WHERE id = ?
`

func (q *Queries) BuscarSolicitudPorID(ctx context.Context, id int64) (Solicitude, error) {
	row := q.db.QueryRowContext(ctx, buscarSolicitudPorID, id)
	var i Solicitude
	err := row.Scan(
		&i.ID,
		&i.CedulaUsuario,
		&i.CantPersonas,
		&i.ParadaOrigen,
		&i.PuntoDestino,
		&i.Estado,
		&i.IDCarrito,
	)
	return i, err
}

const crearSolicitud = `-- name: CrearSolicitud :one
INSERT INTO solicitudes (cedula_usuario, cant_personas, parada_origen, punto_destino, estado, id_carrito) VALUES (?, ?, ?, ?, ?, ?) RETURNING id, cedula_usuario, cant_personas, parada_origen, punto_destino, estado, id_carrito
`

type CrearSolicitudParams struct {
	CedulaUsuario string
	CantPersonas  sql.NullInt64
	ParadaOrigen  sql.NullInt64
	PuntoDestino  sql.NullString
	Estado        sql.NullString
	IDCarrito     sql.NullInt64
}

func (q *Queries) CrearSolicitud(ctx context.Context, arg CrearSolicitudParams) (Solicitude, error) {
	row := q.db.QueryRowContext(ctx, crearSolicitud,
		arg.CedulaUsuario,
		arg.CantPersonas,
		arg.ParadaOrigen,
		arg.PuntoDestino,
		arg.Estado,
		arg.IDCarrito,
	)
	var i Solicitude
	err := row.Scan(
		&i.ID,
		&i.CedulaUsuario,
		&i.CantPersonas,
		&i.ParadaOrigen,
		&i.PuntoDestino,
		&i.Estado,
		&i.IDCarrito,
	)
	return i, err
}

const listarSolicitudes = `-- name: ListarSolicitudes :many
SELECT id, cedula_usuario, cant_personas, parada_origen, punto_destino, estado, id_carrito FROM solicitudes
`

func (q *Queries) ListarSolicitudes(ctx context.Context) ([]Solicitude, error) {
	rows, err := q.db.QueryContext(ctx, listarSolicitudes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Solicitude
	for rows.Next() {
		var i Solicitude
		if err := rows.Scan(
			&i.ID,
			&i.CedulaUsuario,
			&i.CantPersonas,
			&i.ParadaOrigen,
			&i.PuntoDestino,
			&i.Estado,
			&i.IDCarrito,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
