// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_ruta.sql

package sqlcdb_transporte

import (
	"context"
	"database/sql"
)

const actualizarRuta = `-- name: ActualizarRuta :one
UPDATE rutas SET nombre = ?, descripcion = ? WHERE id = ? RETURNING id, nombre, descripcion
`

type ActualizarRutaParams struct {
	Nombre      string
	Descripcion sql.NullString
	ID          int64
}

func (q *Queries) ActualizarRuta(ctx context.Context, arg ActualizarRutaParams) (Ruta, error) {
	row := q.db.QueryRowContext(ctx, actualizarRuta, arg.Nombre, arg.Descripcion, arg.ID)
	var i Ruta
	err := row.Scan(&i.ID, &i.Nombre, &i.Descripcion)
	return i, err
}

const borrarRuta = `-- name: BorrarRuta :execrows
DELETE FROM rutas WHERE id = ?
`

func (q *Queries) BorrarRuta(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarRuta, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarRutaPorID = `-- name: BuscarRutaPorID :one
SELECT id, nombre, descripcion FROM rutas WHERE id = ?
`

func (q *Queries) BuscarRutaPorID(ctx context.Context, id int64) (Ruta, error) {
	row := q.db.QueryRowContext(ctx, buscarRutaPorID, id)
	var i Ruta
	err := row.Scan(&i.ID, &i.Nombre, &i.Descripcion)
	return i, err
}

const crearRuta = `-- name: CrearRuta :one
INSERT INTO rutas (nombre, descripcion) VALUES (?, ?) RETURNING id, nombre, descripcion
`

type CrearRutaParams struct {
	Nombre      string
	Descripcion sql.NullString
}

func (q *Queries) CrearRuta(ctx context.Context, arg CrearRutaParams) (Ruta, error) {
	row := q.db.QueryRowContext(ctx, crearRuta, arg.Nombre, arg.Descripcion)
	var i Ruta
	err := row.Scan(&i.ID, &i.Nombre, &i.Descripcion)
	return i, err
}

const listarRutas = `-- name: ListarRutas :many
SELECT id, nombre, descripcion FROM rutas
`

func (q *Queries) ListarRutas(ctx context.Context) ([]Ruta, error) {
	rows, err := q.db.QueryContext(ctx, listarRutas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ruta
	for rows.Next() {
		var i Ruta
		if err := rows.Scan(&i.ID, &i.Nombre, &i.Descripcion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
