// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_carrito.sql

package sqlcdb_transporte

import (
	"context"
	"database/sql"
)

const actualizarCarrito = `-- name: ActualizarCarrito :one
UPDATE carritos SET nombre_carrito = ?, capacidad = ?, estado = ?, ruta_id = ? WHERE id = ? RETURNING id, nombre_carrito, capacidad, estado, ruta_id
`

type ActualizarCarritoParams struct {
	NombreCarrito string
	Capacidad     int64
	Estado        sql.NullString
	RutaID        sql.NullInt64
	ID            int64
}

func (q *Queries) ActualizarCarrito(ctx context.Context, arg ActualizarCarritoParams) (Carrito, error) {
	row := q.db.QueryRowContext(ctx, actualizarCarrito,
		arg.NombreCarrito,
		arg.Capacidad,
		arg.Estado,
		arg.RutaID,
		arg.ID,
	)
	var i Carrito
	err := row.Scan(
		&i.ID,
		&i.NombreCarrito,
		&i.Capacidad,
		&i.Estado,
		&i.RutaID,
	)
	return i, err
}

const borrarCarrito = `-- name: BorrarCarrito :execrows
DELETE FROM carritos WHERE id = ?
`

func (q *Queries) BorrarCarrito(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarCarrito, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarCarritoPorID = `-- name: BuscarCarritoPorID :one
SELECT id, nombre_carrito, capacidad, estado, ruta_id FROM carritos WHERE id = ?
`

func (q *Queries) BuscarCarritoPorID(ctx context.Context, id int64) (Carrito, error) {
	row := q.db.QueryRowContext(ctx, buscarCarritoPorID, id)
	var i Carrito
	err := row.Scan(
		&i.ID,
		&i.NombreCarrito,
		&i.Capacidad,
		&i.Estado,
		&i.RutaID,
	)
	return i, err
}

const crearCarrito = `-- name: CrearCarrito :one
INSERT INTO carritos (nombre_carrito, capacidad, estado, ruta_id) VALUES (?, ?, ?, ?) RETURNING id, nombre_carrito, capacidad, estado, ruta_id
`

type CrearCarritoParams struct {
	NombreCarrito string
	Capacidad     int64
	Estado        sql.NullString
	RutaID        sql.NullInt64
}

func (q *Queries) CrearCarrito(ctx context.Context, arg CrearCarritoParams) (Carrito, error) {
	row := q.db.QueryRowContext(ctx, crearCarrito,
		arg.NombreCarrito,
		arg.Capacidad,
		arg.Estado,
		arg.RutaID,
	)
	var i Carrito
	err := row.Scan(
		&i.ID,
		&i.NombreCarrito,
		&i.Capacidad,
		&i.Estado,
		&i.RutaID,
	)
	return i, err
}

const listarCarritos = `-- name: ListarCarritos :many
SELECT id, nombre_carrito, capacidad, estado, ruta_id FROM carritos
`

func (q *Queries) ListarCarritos(ctx context.Context) ([]Carrito, error) {
	rows, err := q.db.QueryContext(ctx, listarCarritos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Carrito
	for rows.Next() {
		var i Carrito
		if err := rows.Scan(
			&i.ID,
			&i.NombreCarrito,
			&i.Capacidad,
			&i.Estado,
			&i.RutaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarCarritosPorRuta = `-- name: ListarCarritosPorRuta :many
SELECT id, nombre_carrito, capacidad, estado, ruta_id FROM carritos WHERE ruta_id = ?
`

func (q *Queries) ListarCarritosPorRuta(ctx context.Context, rutaID sql.NullInt64) ([]Carrito, error) {
	rows, err := q.db.QueryContext(ctx, listarCarritosPorRuta, rutaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Carrito
	for rows.Next() {
		var i Carrito
		if err := rows.Scan(
			&i.ID,
			&i.NombreCarrito,
			&i.Capacidad,
			&i.Estado,
			&i.RutaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
