// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_parada.sql

package sqlcdb_transporte

import (
	"context"
	"database/sql"
)

const actualizarParada = `-- name: ActualizarParada :one
UPDATE paradas SET nombre = ?, latitud = ?, longitud = ? WHERE id_parada = ? RETURNING id_parada, nombre, latitud, longitud
`

type ActualizarParadaParams struct {
	Nombre   string
	Latitud  sql.NullFloat64
	Longitud sql.NullFloat64
	IDParada int64
}

func (q *Queries) ActualizarParada(ctx context.Context, arg ActualizarParadaParams) (Parada, error) {
	row := q.db.QueryRowContext(ctx, actualizarParada,
		arg.Nombre,
		arg.Latitud,
		arg.Longitud,
		arg.IDParada,
	)
	var i Parada
	err := row.Scan(
		&i.IDParada,
		&i.Nombre,
		&i.Latitud,
		&i.Longitud,
	)
	return i, err
}

const borrarParada = `-- name: BorrarParada :execrows
DELETE FROM paradas WHERE id_parada = ?
`

func (q *Queries) BorrarParada(ctx context.Context, idParada int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarParada, idParada)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarParadaPorID = `-- name: BuscarParadaPorID :one
SELECT id_parada, nombre, latitud, longitud FROM paradas WHERE id_parada = ?
`

func (q *Queries) BuscarParadaPorID(ctx context.Context, idParada int64) (Parada, error) {
	row := q.db.QueryRowContext(ctx, buscarParadaPorID, idParada)
	var i Parada
	err := row.Scan(
		&i.IDParada,
		&i.Nombre,
		&i.Latitud,
		&i.Longitud,
	)
	return i, err
}

const crearParada = `-- name: CrearParada :one
INSERT INTO paradas (nombre, latitud, longitud) VALUES (?, ?, ?) RETURNING id_parada, nombre, latitud, longitud
`

type CrearParadaParams struct {
	Nombre   string
	Latitud  sql.NullFloat64
	Longitud sql.NullFloat64
}

func (q *Queries) CrearParada(ctx context.Context, arg CrearParadaParams) (Parada, error) {
	row := q.db.QueryRowContext(ctx, crearParada, arg.Nombre, arg.Latitud, arg.Longitud)
	var i Parada
	err := row.Scan(
		&i.IDParada,
		&i.Nombre,
		&i.Latitud,
		&i.Longitud,
	)
	return i, err
}

const listarParadas = `-- name: ListarParadas :many
SELECT id_parada, nombre, latitud, longitud FROM paradas
`

func (q *Queries) ListarParadas(ctx context.Context) ([]Parada, error) {
	rows, err := q.db.QueryContext(ctx, listarParadas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Parada
	for rows.Next() {
		var i Parada
		if err := rows.Scan(
			&i.IDParada,
			&i.Nombre,
			&i.Latitud,
			&i.Longitud,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
