// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql"
	"time"
)

type Acceso struct {
	IDAcceso      int64          `json:"id_acceso"`
	PlacaVehiculo string         `json:"placa_vehiculo"`
	IDPuntoacceso int64          `json:"id_puntoacceso"`
	TiempoEntrada time.Time      `json:"tiempo_entrada"`
	TiempoSalida  sql.NullTime   `json:"tiempo_salida"`
	Estado        string         `json:"estado"`
	Observaciones sql.NullString `json:"observaciones"`
}

type PuntoDeAcceso struct {
	IDPuntoacceso int64  `json:"id_puntoacceso"`
	TipoAcceso    string `json:"tipo_acceso"`
	Ubicacion     string `json:"ubicacion"`
}

type Usuario struct {
	CedulaInt     int64  `json:"cedula_int"`
	NombreUsuario string `json:"nombre_usuario"`
	Contrasena    string `json:"contrasena"`
	Email         string `json:"email"`
	Rol           string `json:"rol"`
}

type Vehiculo struct {
	PlacaVehiculo string `json:"placa_vehiculo"`
	IDUsuario     int64  `json:"id_usuario"`
	TipoUsuario   string `json:"tipo_usuario"`
	Marca         string `json:"marca"`
	Modelo        string `json:"modelo"`
	Color         string `json:"color"`
	Anio          int64  `json:"anio"`
}
