// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_vehiculo.sql

package sqlcdb

import (
	"context"
)

const listarVehiculos = `-- name: ListarVehiculos :many
SELECT placa_vehiculo, id_usuario, Tipo_usuario, Marca, Modelo, Color, Anio
FROM Vehiculos
`

func (q *Queries) ListarVehiculos(ctx context.Context) ([]Vehiculo, error) {
	rows, err := q.db.QueryContext(ctx, listarVehiculos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vehiculo
	for rows.Next() {
		var i Vehiculo
		if err := rows.Scan(
			&i.PlacaVehiculo,
			&i.IDUsuario,
			&i.TipoUsuario,
			&i.Marca,
			&i.Modelo,
			&i.Color,
			&i.Anio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerVehiculoPorPlaca = `-- name: ObtenerVehiculoPorPlaca :one
SELECT placa_vehiculo, id_usuario, Tipo_usuario, Marca, Modelo, Color, Anio
FROM Vehiculos
WHERE placa_vehiculo = ? LIMIT 1
`

func (q *Queries) ObtenerVehiculoPorPlaca(ctx context.Context, placaVehiculo string) (Vehiculo, error) {
	row := q.db.QueryRowContext(ctx, obtenerVehiculoPorPlaca, placaVehiculo)
	var i Vehiculo
	err := row.Scan(
		&i.PlacaVehiculo,
		&i.IDUsuario,
		&i.TipoUsuario,
		&i.Marca,
		&i.Modelo,
		&i.Color,
		&i.Anio,
	)
	return i, err
}

const registrarVehiculo = `-- name: RegistrarVehiculo :one
INSERT INTO Vehiculos (placa_vehiculo, id_usuario, Tipo_usuario, Marca, Modelo, Color, Anio)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING placa_vehiculo, id_usuario, tipo_usuario, marca, modelo, color, anio
`

type RegistrarVehiculoParams struct {
	PlacaVehiculo string `json:"placa_vehiculo"`
	IDUsuario     int64  `json:"id_usuario"`
	TipoUsuario   string `json:"tipo_usuario"`
	Marca         string `json:"marca"`
	Modelo        string `json:"modelo"`
	Color         string `json:"color"`
	Anio          int64  `json:"anio"`
}

func (q *Queries) RegistrarVehiculo(ctx context.Context, arg RegistrarVehiculoParams) (Vehiculo, error) {
	row := q.db.QueryRowContext(ctx, registrarVehiculo,
		arg.PlacaVehiculo,
		arg.IDUsuario,
		arg.TipoUsuario,
		arg.Marca,
		arg.Modelo,
		arg.Color,
		arg.Anio,
	)
	var i Vehiculo
	err := row.Scan(
		&i.PlacaVehiculo,
		&i.IDUsuario,
		&i.TipoUsuario,
		&i.Marca,
		&i.Modelo,
		&i.Color,
		&i.Anio,
	)
	return i, err
}
