// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_punto_acceso.sql

package sqlcdb

import (
	"context"
)

const crearPuntoAcceso = `-- name: CrearPuntoAcceso :one
INSERT INTO Punto_de_acceso (Tipo_acceso, Ubicacion)
VALUES (?, ?)
RETURNING id_puntoacceso, tipo_acceso, ubicacion
`

type CrearPuntoAccesoParams struct {
	TipoAcceso string `json:"tipo_acceso"`
	Ubicacion  string `json:"ubicacion"`
}

func (q *Queries) CrearPuntoAcceso(ctx context.Context, arg CrearPuntoAccesoParams) (PuntoDeAcceso, error) {
	row := q.db.QueryRowContext(ctx, crearPuntoAcceso, arg.TipoAcceso, arg.Ubicacion)
	var i PuntoDeAcceso
	err := row.Scan(&i.IDPuntoacceso, &i.TipoAcceso, &i.Ubicacion)
	return i, err
}

const listarPuntosAcceso = `-- name: ListarPuntosAcceso :many
SELECT ID_puntoacceso, Tipo_acceso, Ubicacion
FROM Punto_de_acceso
`

func (q *Queries) ListarPuntosAcceso(ctx context.Context) ([]PuntoDeAcceso, error) {
	rows, err := q.db.QueryContext(ctx, listarPuntosAcceso)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PuntoDeAcceso
	for rows.Next() {
		var i PuntoDeAcceso
		if err := rows.Scan(&i.IDPuntoacceso, &i.TipoAcceso, &i.Ubicacion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerPuntoAccesoPorId = `-- name: ObtenerPuntoAccesoPorId :one
SELECT ID_puntoacceso, Tipo_acceso, Ubicacion
FROM Punto_de_acceso
WHERE ID_puntoacceso = ? LIMIT 1
`

func (q *Queries) ObtenerPuntoAccesoPorId(ctx context.Context, idPuntoacceso int64) (PuntoDeAcceso, error) {
	row := q.db.QueryRowContext(ctx, obtenerPuntoAccesoPorId, idPuntoacceso)
	var i PuntoDeAcceso
	err := row.Scan(&i.IDPuntoacceso, &i.TipoAcceso, &i.Ubicacion)
	return i, err
}
