// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_usuario.sql

package sqlcdb

import (
	"context"
)

const listarUsuarios = `-- name: ListarUsuarios :many
SELECT Cedula_int, Nombre_usuario, Contrasena, Email, Rol
FROM Usuario
`

func (q *Queries) ListarUsuarios(ctx context.Context) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, listarUsuarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.CedulaInt,
			&i.NombreUsuario,
			&i.Contrasena,
			&i.Email,
			&i.Rol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerUsuarioPorCedula = `-- name: ObtenerUsuarioPorCedula :one
SELECT Cedula_int, Nombre_usuario, Contrasena, Email, Rol
FROM Usuario
WHERE Cedula_int = ? LIMIT 1
`

func (q *Queries) ObtenerUsuarioPorCedula(ctx context.Context, cedulaInt int64) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, obtenerUsuarioPorCedula, cedulaInt)
	var i Usuario
	err := row.Scan(
		&i.CedulaInt,
		&i.NombreUsuario,
		&i.Contrasena,
		&i.Email,
		&i.Rol,
	)
	return i, err
}

const registrarUsuario = `-- name: RegistrarUsuario :one
INSERT INTO Usuario (Cedula_int, Nombre_usuario, Contrasena, Email, Rol)
VALUES (?, ?, ?, ?, ?)
RETURNING cedula_int, nombre_usuario, contrasena, email, rol
`

type RegistrarUsuarioParams struct {
	CedulaInt     int64  `json:"cedula_int"`
	NombreUsuario string `json:"nombre_usuario"`
	Contrasena    string `json:"contrasena"`
	Email         string `json:"email"`
	Rol           string `json:"rol"`
}

func (q *Queries) RegistrarUsuario(ctx context.Context, arg RegistrarUsuarioParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, registrarUsuario,
		arg.CedulaInt,
		arg.NombreUsuario,
		arg.Contrasena,
		arg.Email,
		arg.Rol,
	)
	var i Usuario
	err := row.Scan(
		&i.CedulaInt,
		&i.NombreUsuario,
		&i.Contrasena,
		&i.Email,
		&i.Rol,
	)
	return i, err
}
