// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_acceso.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"
)

const listarAccesos = `-- name: ListarAccesos :many
SELECT ID_acceso, Placa_vehiculo, ID_puntoacceso, Tiempo_entrada, Tiempo_salida, Estado, Observaciones
FROM Acceso
ORDER BY Tiempo_entrada DESC
`

func (q *Queries) ListarAccesos(ctx context.Context) ([]Acceso, error) {
	rows, err := q.db.QueryContext(ctx, listarAccesos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Acceso
	for rows.Next() {
		var i Acceso
		if err := rows.Scan(
			&i.IDAcceso,
			&i.PlacaVehiculo,
			&i.IDPuntoacceso,
			&i.TiempoEntrada,
			&i.TiempoSalida,
			&i.Estado,
			&i.Observaciones,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrarAccesoEntrada = `-- name: RegistrarAccesoEntrada :one
INSERT INTO Acceso (Placa_vehiculo, ID_puntoacceso, Tiempo_entrada, Estado, Observaciones)
VALUES (?, ?, ?, ?, ?)
RETURNING id_acceso, placa_vehiculo, id_puntoacceso, tiempo_entrada, tiempo_salida, estado, observaciones
`

type RegistrarAccesoEntradaParams struct {
	PlacaVehiculo string         `json:"placa_vehiculo"`
	IDPuntoacceso int64          `json:"id_puntoacceso"`
	TiempoEntrada time.Time      `json:"tiempo_entrada"`
	Estado        string         `json:"estado"`
	Observaciones sql.NullString `json:"observaciones"`
}

func (q *Queries) RegistrarAccesoEntrada(ctx context.Context, arg RegistrarAccesoEntradaParams) (Acceso, error) {
	row := q.db.QueryRowContext(ctx, registrarAccesoEntrada,
		arg.PlacaVehiculo,
		arg.IDPuntoacceso,
		arg.TiempoEntrada,
		arg.Estado,
		arg.Observaciones,
	)
	var i Acceso
	err := row.Scan(
		&i.IDAcceso,
		&i.PlacaVehiculo,
		&i.IDPuntoacceso,
		&i.TiempoEntrada,
		&i.TiempoSalida,
		&i.Estado,
		&i.Observaciones,
	)
	return i, err
}

const registrarAccesoSalida = `-- name: RegistrarAccesoSalida :one
UPDATE Acceso
SET Tiempo_salida = ?, Estado = ?, Observaciones = ?
WHERE ID_acceso = ?
RETURNING id_acceso, placa_vehiculo, id_puntoacceso, tiempo_entrada, tiempo_salida, estado, observaciones
`

type RegistrarAccesoSalidaParams struct {
	TiempoSalida  sql.NullTime   `json:"tiempo_salida"`
	Estado        string         `json:"estado"`
	Observaciones sql.NullString `json:"observaciones"`
	IDAcceso      int64          `json:"id_acceso"`
}

func (q *Queries) RegistrarAccesoSalida(ctx context.Context, arg RegistrarAccesoSalidaParams) (Acceso, error) {
	row := q.db.QueryRowContext(ctx, registrarAccesoSalida,
		arg.TiempoSalida,
		arg.Estado,
		arg.Observaciones,
		arg.IDAcceso,
	)
	var i Acceso
	err := row.Scan(
		&i.IDAcceso,
		&i.PlacaVehiculo,
		&i.IDPuntoacceso,
		&i.TiempoEntrada,
		&i.TiempoSalida,
		&i.Estado,
		&i.Observaciones,
	)
	return i, err
}
