// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql"
	"time"
)

type Espacio struct {
	IDEspacio     int64
	IDParqueadero int64
	Numero        int64
	Estado        string
	TipoEspacio   string
}

type Ocupacion struct {
	IDOcupacion   int64
	PlacaVehiculo string
	IDEspacio     int64
	IDAcceso      int64
	HoraInicio    time.Time
	HoraFin       sql.NullTime
}

type Parqueadero struct {
	IDParqueadero int64
	Nombre        string
	Capacidad     int64
	Tipo          string
}
