// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_ocupacion.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"
)

const actualizarOcupacion = `-- name: ActualizarOcupacion :one
UPDATE ocupacion
SET placa_vehiculo = ?, id_espacio = ?, id_acceso = ?, hora_inicio = ?, hora_fin = ?
WHERE id_ocupacion = ?
RETURNING id_ocupacion, placa_vehiculo, id_espacio, id_acceso, hora_inicio, hora_fin
`

type ActualizarOcupacionParams struct {
	PlacaVehiculo string
	IDEspacio     int64
	IDAcceso      int64
	HoraInicio    time.Time
	HoraFin       sql.NullTime
	IDOcupacion   int64
}

func (q *Queries) ActualizarOcupacion(ctx context.Context, arg ActualizarOcupacionParams) (Ocupacion, error) {
	row := q.db.QueryRowContext(ctx, actualizarOcupacion,
		arg.PlacaVehiculo,
		arg.IDEspacio,
		arg.IDAcceso,
		arg.HoraInicio,
		arg.HoraFin,
		arg.IDOcupacion,
	)
	var i Ocupacion
	err := row.Scan(
		&i.IDOcupacion,
		&i.PlacaVehiculo,
		&i.IDEspacio,
		&i.IDAcceso,
		&i.HoraInicio,
		&i.HoraFin,
	)
	return i, err
}

const borrarOcupacion = `-- name: BorrarOcupacion :execrows
DELETE FROM ocupacion WHERE id_ocupacion = ?
`

func (q *Queries) BorrarOcupacion(ctx context.Context, idOcupacion int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarOcupacion, idOcupacion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarOcupacionPorID = `-- name: BuscarOcupacionPorID :one
SELECT id_ocupacion, placa_vehiculo, id_espacio, id_acceso, hora_inicio, hora_fin
FROM ocupacion
WHERE id_ocupacion = ?
`

func (q *Queries) BuscarOcupacionPorID(ctx context.Context, idOcupacion int64) (Ocupacion, error) {
	row := q.db.QueryRowContext(ctx, buscarOcupacionPorID, idOcupacion)
	var i Ocupacion
	err := row.Scan(
		&i.IDOcupacion,
		&i.PlacaVehiculo,
		&i.IDEspacio,
		&i.IDAcceso,
		&i.HoraInicio,
		&i.HoraFin,
	)
	return i, err
}

const cerrarOcupacion = `-- name: CerrarOcupacion :one
UPDATE ocupacion
SET hora_fin = ?
WHERE id_ocupacion = ?
RETURNING id_ocupacion, placa_vehiculo, id_espacio, id_acceso, hora_inicio, hora_fin
`

type CerrarOcupacionParams struct {
	HoraFin     sql.NullTime
	IDOcupacion int64
}

func (q *Queries) CerrarOcupacion(ctx context.Context, arg CerrarOcupacionParams) (Ocupacion, error) {
	row := q.db.QueryRowContext(ctx, cerrarOcupacion, arg.HoraFin, arg.IDOcupacion)
	var i Ocupacion
	err := row.Scan(
		&i.IDOcupacion,
		&i.PlacaVehiculo,
		&i.IDEspacio,
		&i.IDAcceso,
		&i.HoraInicio,
		&i.HoraFin,
	)
	return i, err
}

const crearOcupacion = `-- name: CrearOcupacion :one
INSERT INTO ocupacion (placa_vehiculo, id_espacio, id_acceso, hora_inicio)
VALUES (?, ?, ?, ?)
RETURNING id_ocupacion, placa_vehiculo, id_espacio, id_acceso, hora_inicio, hora_fin
`

type CrearOcupacionParams struct {
	PlacaVehiculo string
	IDEspacio     int64
	IDAcceso      int64
	HoraInicio    time.Time
}

func (q *Queries) CrearOcupacion(ctx context.Context, arg CrearOcupacionParams) (Ocupacion, error) {
	row := q.db.QueryRowContext(ctx, crearOcupacion,
		arg.PlacaVehiculo,
		arg.IDEspacio,
		arg.IDAcceso,
		arg.HoraInicio,
	)
	var i Ocupacion
	err := row.Scan(
		&i.IDOcupacion,
		&i.PlacaVehiculo,
		&i.IDEspacio,
		&i.IDAcceso,
		&i.HoraInicio,
		&i.HoraFin,
	)
	return i, err
}

const listarOcupaciones = `-- name: ListarOcupaciones :many
SELECT id_ocupacion, placa_vehiculo, id_espacio, id_acceso, hora_inicio, hora_fin
FROM ocupacion
`

func (q *Queries) ListarOcupaciones(ctx context.Context) ([]Ocupacion, error) {
	rows, err := q.db.QueryContext(ctx, listarOcupaciones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ocupacion
	for rows.Next() {
		var i Ocupacion
		if err := rows.Scan(
			&i.IDOcupacion,
			&i.PlacaVehiculo,
			&i.IDEspacio,
			&i.IDAcceso,
			&i.HoraInicio,
			&i.HoraFin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarOcupacionesActivasPorEspacio = `-- name: ListarOcupacionesActivasPorEspacio :many
SELECT id_ocupacion, placa_vehiculo, id_espacio, id_acceso, hora_inicio, hora_fin
FROM ocupacion
WHERE id_espacio = ? AND hora_fin IS NULL
`

func (q *Queries) ListarOcupacionesActivasPorEspacio(ctx context.Context, idEspacio int64) ([]Ocupacion, error) {
	rows, err := q.db.QueryContext(ctx, listarOcupacionesActivasPorEspacio, idEspacio)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ocupacion
	for rows.Next() {
		var i Ocupacion
		if err := rows.Scan(
			&i.IDOcupacion,
			&i.PlacaVehiculo,
			&i.IDEspacio,
			&i.IDAcceso,
			&i.HoraInicio,
			&i.HoraFin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
