// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_parqueadero.sql

package sqlcdb

import (
	"context"
)

const actualizarParqueadero = `-- name: ActualizarParqueadero :one
UPDATE parqueaderos
SET nombre = ?, capacidad = ?, tipo = ?
WHERE id_parqueadero = ?
RETURNING id_parqueadero, nombre, capacidad, tipo
`

type ActualizarParqueaderoParams struct {
	Nombre        string
	Capacidad     int64
	Tipo          string
	IDParqueadero int64
}

func (q *Queries) ActualizarParqueadero(ctx context.Context, arg ActualizarParqueaderoParams) (Parqueadero, error) {
	row := q.db.QueryRowContext(ctx, actualizarParqueadero,
		arg.Nombre,
		arg.Capacidad,
		arg.Tipo,
		arg.IDParqueadero,
	)
	var i Parqueadero
	err := row.Scan(
		&i.IDParqueadero,
		&i.Nombre,
		&i.Capacidad,
		&i.Tipo,
	)
	return i, err
}

const borrarParqueadero = `-- name: BorrarParqueadero :execrows
DELETE FROM parqueaderos WHERE id_parqueadero = ?
`

func (q *Queries) BorrarParqueadero(ctx context.Context, idParqueadero int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarParqueadero, idParqueadero)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarParqueaderoPorID = `-- name: BuscarParqueaderoPorID :one
SELECT id_parqueadero, nombre, capacidad, tipo FROM parqueaderos
WHERE id_parqueadero = ?
`

func (q *Queries) BuscarParqueaderoPorID(ctx context.Context, idParqueadero int64) (Parqueadero, error) {
	row := q.db.QueryRowContext(ctx, buscarParqueaderoPorID, idParqueadero)
	var i Parqueadero
	err := row.Scan(
		&i.IDParqueadero,
		&i.Nombre,
		&i.Capacidad,
		&i.Tipo,
	)
	return i, err
}

const crearParqueadero = `-- name: CrearParqueadero :one
INSERT INTO parqueaderos (nombre, capacidad, tipo)
VALUES (?, ?, ?)
RETURNING id_parqueadero, nombre, capacidad, tipo
`

type CrearParqueaderoParams struct {
	Nombre    string
	Capacidad int64
	Tipo      string
}

func (q *Queries) CrearParqueadero(ctx context.Context, arg CrearParqueaderoParams) (Parqueadero, error) {
	row := q.db.QueryRowContext(ctx, crearParqueadero, arg.Nombre, arg.Capacidad, arg.Tipo)
	var i Parqueadero
	err := row.Scan(
		&i.IDParqueadero,
		&i.Nombre,
		&i.Capacidad,
		&i.Tipo,
	)
	return i, err
}

const listarParqueaderos = `-- name: ListarParqueaderos :many
SELECT id_parqueadero, nombre, capacidad, tipo FROM parqueaderos
`

func (q *Queries) ListarParqueaderos(ctx context.Context) ([]Parqueadero, error) {
	rows, err := q.db.QueryContext(ctx, listarParqueaderos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Parqueadero
	for rows.Next() {
		var i Parqueadero
		if err := rows.Scan(
			&i.IDParqueadero,
			&i.Nombre,
			&i.Capacidad,
			&i.Tipo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
