// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_espacio.sql

package sqlcdb

import (
	"context"
)

const actualizarEspacio = `-- name: ActualizarEspacio :one
UPDATE espacios
SET id_parqueadero = ?, numero = ?, estado = ?, tipo_espacio = ?
WHERE id_espacio = ?
RETURNING id_espacio, id_parqueadero, numero, estado, tipo_espacio
`

type ActualizarEspacioParams struct {
	IDParqueadero int64
	Numero        int64
	Estado        string
	TipoEspacio   string
	IDEspacio     int64
}

func (q *Queries) ActualizarEspacio(ctx context.Context, arg ActualizarEspacioParams) (Espacio, error) {
	row := q.db.QueryRowContext(ctx, actualizarEspacio,
		arg.IDParqueadero,
		arg.Numero,
		arg.Estado,
		arg.TipoEspacio,
		arg.IDEspacio,
	)
	var i Espacio
	err := row.Scan(
		&i.IDEspacio,
		&i.IDParqueadero,
		&i.Numero,
		&i.Estado,
		&i.TipoEspacio,
	)
	return i, err
}

const borrarEspacio = `-- name: BorrarEspacio :execrows
DELETE FROM espacios WHERE id_espacio = ?
`

func (q *Queries) BorrarEspacio(ctx context.Context, idEspacio int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarEspacio, idEspacio)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarEspacioPorID = `-- name: BuscarEspacioPorID :one
SELECT id_espacio, id_parqueadero, numero, estado, tipo_espacio FROM espacios
WHERE id_espacio = ?
`

func (q *Queries) BuscarEspacioPorID(ctx context.Context, idEspacio int64) (Espacio, error) {
	row := q.db.QueryRowContext(ctx, buscarEspacioPorID, idEspacio)
	var i Espacio
	err := row.Scan(
		&i.IDEspacio,
		&i.IDParqueadero,
		&i.Numero,
		&i.Estado,
		&i.TipoEspacio,
	)
	return i, err
}

const crearEspacio = `-- name: CrearEspacio :one
INSERT INTO espacios (id_parqueadero, numero, estado, tipo_espacio)
VALUES (?, ?, ?, ?)
RETURNING id_espacio, id_parqueadero, numero, estado, tipo_espacio
`

type CrearEspacioParams struct {
	IDParqueadero int64
	Numero        int64
	Estado        string
	TipoEspacio   string
}

func (q *Queries) CrearEspacio(ctx context.Context, arg CrearEspacioParams) (Espacio, error) {
	row := q.db.QueryRowContext(ctx, crearEspacio,
		arg.IDParqueadero,
		arg.Numero,
		arg.Estado,
		arg.TipoEspacio,
	)
	var i Espacio
	err := row.Scan(
		&i.IDEspacio,
		&i.IDParqueadero,
		&i.Numero,
		&i.Estado,
		&i.TipoEspacio,
	)
	return i, err
}

const listarEspacios = `-- name: ListarEspacios :many
SELECT id_espacio, id_parqueadero, numero, estado, tipo_espacio FROM espacios
`

func (q *Queries) ListarEspacios(ctx context.Context) ([]Espacio, error) {
	rows, err := q.db.QueryContext(ctx, listarEspacios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Espacio
	for rows.Next() {
		var i Espacio
		if err := rows.Scan(
			&i.IDEspacio,
			&i.IDParqueadero,
			&i.Numero,
			&i.Estado,
			&i.TipoEspacio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarEspaciosPorParqueadero = `-- name: ListarEspaciosPorParqueadero :many
SELECT id_espacio, id_parqueadero, numero, estado, tipo_espacio FROM espacios
WHERE id_parqueadero = ?
`

func (q *Queries) ListarEspaciosPorParqueadero(ctx context.Context, idParqueadero int64) ([]Espacio, error) {
	rows, err := q.db.QueryContext(ctx, listarEspaciosPorParqueadero, idParqueadero)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Espacio
	for rows.Next() {
		var i Espacio
		if err := rows.Scan(
			&i.IDEspacio,
			&i.IDParqueadero,
			&i.Numero,
			&i.Estado,
			&i.TipoEspacio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
